services:

    rs_queue.data_collector:
        class: RSQueueBundle\Collector\RSQueueCollector
        tags:
            - { name: data_collector, template: "@RSQueue/Collector/rsqueue.html.twig", id: "rsqueue_collector" }
            - { name: kernel.event_listener, event: rsqueue.producer, method: onProducerAction }
            - { name: kernel.event_listener, event: rsqueue.publisher, method: onPublisherAction }
