sudo: required

language: php

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.1
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.1
    - php: 7.2

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - git clone git://github.com/nicolasff/phpredis.git
    - cd phpredis && phpize && ./configure && make && sudo make install && cd ..
    - echo "extension=redis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - docker pull cheprasov/redis-for-tests:latest;
    - docker pull cheprasov/redis-cluster-for-tests:latest;
    - |
       docker run -i -t -d \
         -p 127.0.0.1:6379:6381 \
         -p 127.0.0.1:6382:6382 \
         -p 127.0.0.1:6383:6383 \
         -p 127.0.0.1:6384:6384 \
         -p 127.0.0.1:6385:6385 \
         -p 127.0.0.1:6386:6386 \
         -p 127.0.0.1:6387:6387 \
         -p 127.0.0.1:6388:6388 \
         -p 127.0.0.1:6389:6389 \
         -p 127.0.0.1:6390:6390 \
         cheprasov/redis-for-tests
    - |
       docker run -i -t -d \
         -p 127.0.0.1:7001:7001 \
         -p 127.0.0.1:7002:7002 \
         -p 127.0.0.1:7003:7003 \
         -p 127.0.0.1:7004:7004 \
         -p 127.0.0.1:7005:7005 \
         -p 127.0.0.1:7006:7006 \
         cheprasov/redis-cluster-for-tests
    - docker ps;
    - sleep 5;

install: composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit
